#!/bin/sh



sudo mkdir /usr/escpos
cd /usr/escpos
sudo wget https://pypi.python.org/packages/82/63/901324c6f808dc2a20d51233445f5b040035ef714a9ba5f9ccc8a0733b7c/python-escpos-1.0.9.tar.gz
sudo tar -xvzf python-escpos-1.0.9.tar.gz
cd /usr/escpos/python-escpos-1.0.9
sudo python setup.py build
sudo python setup.py install
sudo apt-get install -y python-pip
sudo pip install pyserial
sudo apt-get install nodejs npm
sudo npm install shelljs -g
sudo npm install ws -g
sudo rm -r /usr/escpos
sudo chmod 777 /usr/Shop_chain -R
Green='\033[0;32m'
Red='\033[0;31m'
NC='\033[0m'
printf "===================================${Red} Install successfull ${NC}===================================\n\n========================================${Red} IMPORTANT ${NC}========================================${Green}\n1) Put your shop name in /usr/Shop_chain/Shop_name.txt\n\n2) Replace the logo.png with your logo of size 200x100 or less with same name.\n\n\n\n\n${NC}" 


#DEBHELPER#
exit 0
