.TH EPSON 1
.SH NAME
epson \- It prints a receipt on epson printer connected via usb to the device
.SH SYNOPSIS
.B epson
[\fB\Item_1_no\fR]
[\fB\Item_1_cost\fR]
.IR ...
.SH DESCRIPTION
.B epson
The arguments given via command line are added to the list and the total of their cost is taken to print final receipt.
.SH AUTHOR
Tanmay Muley <tanmay_muley@yahoo.com>
