.TH ZEBRA 1
.SH NAME
zebra \- It prints a label on zebra printer connected via usb to the device.
.SH SYNOPSIS
.B zebra
[\fB\Item_name\fR]
[\fB\Delivery-date\fR]
[\fB\Zebra-printer-queue\fR]
.SH DESCRIPTION
.B epson
The arguments given via command line are added to the custom format of label provided to print th final label.
.SH AUTHOR
Tanmay Muley <tanmay_muley@yahoo.com>
